// Code generated by MockGen. DO NOT EDIT.
// Source: .gen/go/cadence/workflowservicetest/client.go

// Package mock_workflowservicetest is a generated GoMock package.
package mock_workflowservicetest
