// Code generated by MockGen. DO NOT EDIT.
// Source: .gen/go/matching/matchingservicetest/client.go

// Package mock_matchingservicetest is a generated GoMock package.
package mock_matchingservicetest
